## MariaDB 

version: "3.8" #Docker Engine에 따른 Docker-compose version

services:
  mariadb:
    image: "mariadb:${tag}"
    container_name: "mariadb-${tag}"
    environment:
      - "MARIADB_DATABASE=${mariadb_database}"
      - "MARIADB_USER=${mariadb_user}"
      - "MARIADB_PASSWORD=${mariadb_password}"
      - "MARIADB_ROOT_PASSWORD=${mariadb_root_password}"
    ports:
      - "3306:3306"

